{
 "title": "APM Dashboard",
 "description": "APM dashboard for monitoring OpenTelemetry-based services.  \n\nInstrument your applications using OpenTelemetry SDKs and send traces, metrics, and logs to Jaeger for traces, a Prometheus-compatible database for metrics, and OpenSearch for logs. This dashboard provides a centralized view of your application's health and performance. ",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Metrics", "query": "prometheus" },
   { "name": "jaeger_datasource", "label": "Traces", "query": "jaeger" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "service.namespace=${service_namespace}, service.name=${service_name}, deployment.environment.name=${deployment_environment_name}",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><img src=\"https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png\" alt=\"OpenTelemetry Icon\" width=\"25\" height=\"\"> Service ${service_namespace}/${service_name}</h1>\n"
   }
  },
  {
   "title": "Latest metrics received",
   "type": "stat",
   "description": "Shows the timestamp of the latest metrics received in the past 24h.",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(sum by (job) (target_info{job=\"$job\"}) or absent{})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Server RED Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "HTTP & RPC endpoints aggregation on the `http.server.request.duration` & `rpc.server.duration` metrics.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration and https://opentelemetry.io/docs/specs/semconv/rpc/rpc-metrics/#metric-rpcserverduration",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, job) (\n    rate(\n      http_server_request_duration_seconds_bucket{        \n        job=\"$job\"\n      }[$__rate_interval]\n    )\n  )\n)\n\nor \n\nhistogram_quantile(\n  0.95,\n  sum by (le, job) (\n    rate(\n      http_server_duration_milliseconds_bucket{        \n        job=\"$job\"\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "HTTP p95"
    },
    {
     "expr": "(avg by (job) (\n  rate(\n    http_server_request_duration_seconds_sum{\n      job=\"$job\"\n    }[$__rate_interval]\n  )\n)\n/\navg by (job) (\n  rate(\n    http_server_request_duration_seconds_count{      \n      job=\"$job\"\n    }[$__rate_interval]\n  )\n))\n\nor \n\n(avg by (job) (\n  rate(\n    http_server_duration_milliseconds_sum{\n      job=\"$job\"\n    }[$__rate_interval]\n  )\n)\n/\navg by (job) (\n  rate(\n    http_server_duration_milliseconds_count{      \n      job=\"$job\"\n    }[$__rate_interval]\n  )\n))",
     "legendFormat": "HTTP avg"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, job) (\n    rate(\n      rpc_server_duration_milliseconds_bucket{\n        job=\"$job\"\n      }[$__rate_interval]\n    ) / 1000\n  )\n)",
     "legendFormat": "RPC p95"
    },
    {
     "expr": "avg by (job) (\n  rate(\n    rpc_server_duration_milliseconds_sum{\n      job=\"$job\"\n    }[$__rate_interval]\n  ) / 1000\n)\n/\navg by (job) (\n  rate(\n    rpc_server_duration_milliseconds_count{\n      job=\"$job\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "RPC avg"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "description": "HTTP and RPC endpoints aggregation on the `http.server.request.duration` and `rpc.server.duration` metrics. \n\nErrors are identified by : \n* `http.response.status_code=~\"5..\"`\n* `rpc.grpc.status_code!=\"0\"`\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration\n",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((\n    (sum by(job) (rate(http_server_request_duration_seconds_count{job=\"$job\", http_response_status_code=~\"5..\"}[$__rate_interval])) * 100) \n    / \n    sum by(job) (rate(http_server_request_duration_seconds_count{job=\"$job\"}[$__rate_interval]))\n)\nor\n(\n    0\n    * \n    sum by(job) (rate(http_server_request_duration_seconds_count{job=\"$job\"}[$__rate_interval]))\n))\n\nor \n\n((\n    (sum by(job) (rate(http_server_duration_milliseconds_count{job=\"$job\", http_status_code=~\"5..\"}[$__rate_interval])) * 100) \n    / \n    sum by(job) (rate(http_server_duration_milliseconds_count{job=\"$job\"}[$__rate_interval]))\n)\nor\n(\n    0\n    * \n    sum by(job) (rate(http_server_duration_milliseconds_count{job=\"$job\"}[$__rate_interval]))\n))",
     "legendFormat": "HTTP 5xx errors"
    },
    {
     "expr": "((sum without (rpc_grpc_status_code, instance) (rate(rpc_server_duration_milliseconds_count{job=\"$job\", rpc_grpc_status_code!=\"0\"}[$__rate_interval])) * 100) / sum without (rpc_grpc_status_code, instance) (rate(rpc_server_duration_milliseconds_count{job=\"$job\"}[$__rate_interval])))\nor\n(0 * sum without (rpc_grpc_status_code, instance) (rate(rpc_server_duration_milliseconds_count{job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "RPC errors"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "HTTP & RPC endpoints aggregation on the `http.server.request.duration` & `rpc.server.duration` metrics.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_count{job=\"$job\"}[$__rate_interval])) by (job)) or (sum(rate(http_server_duration_milliseconds_count{job=\"$job\"}[$__rate_interval])) by (job)) ",
     "legendFormat": "HTTP requests"
    },
    {
     "expr": "(sum(rate(rpc_server_duration_milliseconds_count{job=\"$job\"}[$__rate_interval])) by (job)) * $__interval_ms / 1000",
     "legendFormat": "RPC requests"
    }
   ]
  },
  {
   "title": "HTTP Operations",
   "type": "table",
   "description": "Inbound HTTP operations of the service (aka HTTP endpoints) based on the `http.server.request.duration` metric.\n\nErrors are identified by `http.response.status_code=~\"5..\"`.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (operation) (\n    label_join(\n            rate(http_server_request_duration_seconds_count{job=\"$job\"}[$__rate_interval]),\n            \"operation\",\n            \" \",\n            \"http_request_method\",\n            \"http_route\"\n    )\n)\n\nor\n\nsum by (operation) (\n    label_join(\n            rate(http_server_duration_milliseconds_count{job=\"$job\"}[$__rate_interval]),\n            \"operation\",\n            \" \",\n            \"http_method\",\n            \"http_route\"\n    )\n)",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "(\n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{job=\"$job\", http_response_status_code=~\"5..\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n     / \n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{job=\"$job\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n    ) or (0 * \n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{job=\"$job\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n)\n\nor\n\n(\n        sum by (operation) (\n            label_join(\n                rate(http_server_duration_milliseconds_count{job=\"$job\", http_status_code=~\"5..\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_method\",\n                \"http_route\"\n            )\n        )\n     / \n        sum by (operation) (\n            label_join(\n                rate(http_server_duration_milliseconds_count{job=\"$job\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_method\",\n                \"http_route\"\n            )\n        )\n    ) or (0 * \n        sum by (operation) (\n            label_join(\n                rate(http_server_duration_milliseconds_count{job=\"$job\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_method\",\n                \"http_route\"\n            )\n        )\n)",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "histogram_quantile(\n     0.99,\n        sum by (le, operation) (\n            label_join(\n            rate(http_server_request_duration_seconds_bucket{job=\"$job\"}[5m]),\n            \"operation\",\n            \" \",\n            \"http_request_method\",\n            \"http_route\"\n            )\n        )\n)\n\nor \n\nhistogram_quantile(\n     0.99,\n        sum by (le, operation) (\n            label_join(\n            rate(http_server_duration_milliseconds_bucket{job=\"$job\"}[5m]),\n            \"operation\",\n            \" \",\n            \"http_method\",\n            \"http_route\"\n            )\n        )\n)\n    ",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Outbound Services and Databases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Outbound HTTP Services",
   "type": "table",
   "description": "HTTP calls made by the service based on the `http.client.request.duration` metric.\n\nCalls broken done by remote `server.address` and by `http.request.method`.\n\nSee https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpclientrequestduration",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "\nsum by (outbound_service) (\n        label_join(\n            rate(http_client_request_duration_seconds_count{job=\"$job\"}[$__rate_interval]),\n            \"outbound_service\",\n            \" \",\n            \"server_address\",\n            \"http_request_method\",\n            \"url_template\"\n        )\n)\n\nor\n\nsum by (outbound_service) (\n        label_join(\n            rate(http_client_duration_milliseconds_count{job=\"$job\"}[$__rate_interval]),\n            \"outbound_service\",\n            \" \",\n            \"server_address\",\n            \"http_method\",\n            \"url_template\"\n        )\n)",
     "legendFormat": "{{server_address}} {{http_request_method}} {{url_template}}"
    },
    {
     "expr": "(\n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{job=\"$job\", http_response_status_code=~\"5..\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n     / \n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{job=\"$job\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n    ) or (0 * \n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{job=\"$job\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n)\n\nor\n\n(\n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_duration_milliseconds_count{job=\"$job\", http_status_code=~\"5..\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_method\",\n                \"url_template\"\n            )\n        )\n     / \n        sum by (outbound_service) (\n            label_join(\n                rate(hhttp_client_duration_milliseconds_count{job=\"$job\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_method\",\n                \"url_template\"\n            )\n        )\n    ) or (0 * \n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_duration_milliseconds_count{job=\"$job\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_method\",\n                \"url_template\"\n            )\n        )\n)",
     "legendFormat": "{{server_address}} {{http_request_method}} {{url_template}}"
    },
    {
     "expr": "\nhistogram_quantile(\n    0.99,\n    sum by (le, outbound_service) (\n        label_join(\n        rate(http_client_request_duration_seconds_bucket{job=\"$job\"}[5m]),\n        \"outbound_service\",\n        \" \",\n        \"server_address\",\n        \"http_request_method\",\n        \"url_template\"\n        )\n    )\n)\n\nor \n\nhistogram_quantile(\n    0.99,\n    sum by (le, outbound_service) (\n        label_join(\n        rate(http_client_duration_milliseconds_bucket{job=\"$job\"}[5m]),\n        \"outbound_service\",\n        \" \",\n        \"server_address\",\n        \"http_method\",\n        \"url_template\"\n        )\n    )\n)",
     "legendFormat": "{{server_address}} {{http_request_method}} {{url_template}}"
    }
   ]
  }
 ]
}
{
 "title": "Demo Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows RED metrics for the selected service, as generated by the spanmetrics connector in the OpenTelemetry Collector.\nIf the selected service emits logs, the logs will also be displayed.\nCustom metrics generated by some services are also displayed. \n<br/>\nChart panels may require 5 minutes after the Demo is started before rendering data."
   }
  },
  { "title": "Spanmetrics (RED metrics)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Requests Rate by Span Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (span_name) (rate(traces_span_metrics_duration_milliseconds_count{job=\"$job\",span_name=~\".*(GET|POST|PUT|DELETE).*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate by Span Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "sum by (span_name) (rate(traces_span_metrics_calls_total{status_code=\"STATUS_CODE_ERROR\", job=\"${job}\"}[$__rate_interval]))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  {
   "title": "Average Duration by Span Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_span_metrics_duration_milliseconds_bucket{job=\"$job\",span_name=~\".*(GET|POST|PUT|DELETE).*\"}[$__rate_interval])) by (le, span_name))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  { "title": "Service Dependency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Service Dependency",
   "type": "nodeGraph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  }
 ]
}
{
 "title": "Spanmetrics Demo Dashboard",
 "description": "Spanmetrics way of demo application view.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "span_name",
    "query": {
     "query": "query_result(sum ({__name__=~\".*traces_span_metrics_calls_total\",service_name=~\"$service\"})  by (span_name))"
    }
   },
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard uses RED metrics generated for all services by the spanmetrics connector configured in the OpenTelemetry Collector.\n<br>\nChart panels may require 5 minutes after the Demo is started before rendering data."
   }
  },
  {
   "title": "Service Level - Throughput and Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Top 3x3 - Service Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7,histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{job=~\"$job\", span_name=~\"$span_name\"}[$__range])) by (le,job)))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum by (job) (rate(traces_span_metrics_calls_total{job=~\"$job\", span_name=~\"$span_name\"}[$__range])))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean ERROR Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum(rate(traces_span_metrics_calls_total{status_code=\"STATUS_CODE_ERROR\",job=~\"$job\", span_name=~\"$span_name\"}[$__range])) by (job))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "span_names Level - Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Top 7 span_names and Errors  (APM Table)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(7, sum(rate(traces_span_metrics_calls_total{job=~\"$job\", span_name=~\"$span_name\"}[$__range])) by (span_name,job)) "
    },
    {
     "expr": "topk(7, sum(rate(traces_span_metrics_calls_total{status_code=\"STATUS_CODE_ERROR\",job=~\"$job\", span_name=~\"$span_name\"}[$__range])) by (span_name,job))"
    }
   ]
  },
  { "title": "span_name Level - Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Top 3x3 - span_name Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7,histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{job=~\"$job\", span_name=~\"$span_name\"}[$__range])) by (le,span_name)))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Highest Endpoint Latencies  Mean Over Range ",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7, sum by (span_name,job)(increase(traces_span_metrics_duration_milliseconds_sum{job=~\"${job}\", span_name=~\"$span_name\"}[5m]) / increase(traces_span_metrics_duration_milliseconds_count{job=~\"${job}\",span_name=~\"$span_name\"}[5m\n])))",
     "legendFormat": "{{span_name}} [{{service_name}}]"
    }
   ]
  }
 ]
}