# Jaeger
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.72.0
          args:
            - "--memory.max-traces=5000"
            - "--query.base-path=/jaeger/ui"
            - "--prometheus.server-url=http://prometheus:9090"
            - "--prometheus.query.normalize-calls=true"
            - "--prometheus.query.normalize-duration=true"
          ports:
            - containerPort: 16686 # UI
            - containerPort: 4317  # OTLP gRPC
          env:
            - name: METRICS_STORAGE_TYPE
              value: "prometheus"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
    - name: ui
      protocol: TCP
      port: 16686
      targetPort: 16686
      nodePort: 30093
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
